### PR TITLE
Cleanup to register "Proteus" on npmjs.org

### PR DESCRIPTION
**Pull request by bennyn**

### CODE REVIEW

**Comment by wrl** [comment]
Does this necessitate re-adding Bower support? As it stands, Proteus depends on `cbor-codec` and some variant of `libsodium`, and the Bower support doesn't ensure that those dependencies are satisfied. If at all possible, I would prefer to have the package management be all-npm.

Is checking in the transpiled Coffeescript output a requirement for publishing a NPM package, or could we also avoid doing that?

**Comment by bennyn** [comment]
The Bower support is just a preparation. In the future it should be possible to get the Proteus dependency isolated from Cryptobox. But for now publishing on https://www.npmjs.com/ has focus. Therefore we need to publish the JavaScript files because we cannot assume that clients will have a CoffeeScript compiler.

I can also remove the `bower.json` for now if you prefer?

**Comment by wrl** [comment]
Yeah, I'd prefer to actually not have Bower in the picture at all. I'd really prefer to just keep this a Node module which is easy to use via Webpack/Browserify for front-end purposes.

With regards to the transpiled output – checking in generated output still doesn't sit well with me and I'd like to avoid that if possible. Is there a way we can build the requisite NPM module with the transpiled Javascript but still not check it in?

In either case, `"coffee-script"` should probably be moved to dev-dependencies if we don't want downstream dependencies to need it installed.

**Comment by bennyn** [comment]
Ok, I removed the `bower.json` and added a `npm prepublish` script.

From the [npm documentation](https://docs.npmjs.com/misc/scripts):
> If you need to perform operations on your package before it is used, in a way that is not dependent on the operating system or architecture of the target system, use a prepublish script. This includes tasks such as: Compiling CoffeeScript source code into JavaScript.

So the `prepublish` script meets perfectly our requirements. Another advantage of the `prepublish` script is that it is executed during a local `npm install`, which means that we can drop our `install` script in favor of the `prepublish` script.

**Comment by wrl** [comment]
Oh, perfect! Nice find on `prepublish`.

Looks good to me now, will get this merged in.

**Pull request merged**
