### PR TITLE
Add Prettier

### PR DESCRIPTION
**Pull request by lipis**
@bennyn these ones needs to be addressed..

```
/home/travis/build/wireapp/proteus.js/test/session/SessionSpec.js
   47:25  error  'message' is already declared in the upper scope    no-shadow
   86:12  error  'alice_store' is assigned a value but never used    no-unused-vars
  583:9   error  'bob' is assigned a value but never used            no-unused-vars
  915:13  error  'hello_bob' is already declared in the upper scope  no-shadow
  925:21  error  'session' is already declared in the upper scope    no-shadow
```

### CODE REVIEW

**Comment by bennyn** [comment]
@lipis: Easy to fix. Just removed the unused variables and rename the ones that have been already declared in the upper scope. You can do it within this PR.

**Comment by lipis** [comment]
@bennyn are you OK with that: https://github.com/wireapp/proteus.js/pull/90/commits/2f9430822437cafcaefc70f71db56e24c367b25e?

**Comment by bennyn** [comment]
No. Names like `message_` & `session_` look strange and `eslint-disable no-unused-vars` is a heavy fallback. Just revert that. I will jump into your branch to fix it.

**Comment by lipis** [comment]
also there other issues with tests.. I added `use strict` to this file.. but it looks like something is broken :/

**Comment by lipis** [comment]
reverted the last changes

**Comment by bennyn** [comment]
Let's check with @ffflorian about the tests on Monday.

**Comment by ffflorian** [comment]
So after fixing the names the tests still fail with a lot of `TypeError: Right-hand side of 'instanceof' is not callable` errors.

This is probably due to the recently added `'use strict'` operator which apparently doesn't allow our setup with forbidding functions to be callable (`new()` instead of `new ...()`).

<details>
<summary>Test Log</summary>

```
$ yarn test
yarn run v1.2.1
$ yarn dist && yarn test:script && yarn test:node
Hash: 6211b192331b57b9a511                                                            
Version: webpack 3.7.1
Time: 387ms
         Asset    Size  Chunks                    Chunk Names
    proteus.js  187 kB       0  [emitted]  [big]  filename
proteus.js.map  238 kB       0  [emitted]         filename
   [4] ./src/proteus/keys/PublicKey.js 3.01 kB {0} [built]
   [6] ./src/proteus/errors/ProteusError.js 1.34 kB {0} [built]
   [7] ./src/proteus/keys/KeyPair.js 3.73 kB {0} [built]
   [8] ./src/proteus/keys/IdentityKey.js 2.46 kB {0} [built]
   [9] ./src/proteus/message/CipherMessage.js 3.36 kB {0} [built]
  [10] ./src/proteus/errors/DecodeError.js 2.07 kB {0} [built]
  [11] ./src/proteus/errors/DecryptError.js 3.14 kB {0} [built]
  [12] ./src/proteus/keys/IdentityKeyPair.js 2.99 kB {0} [built]
  [13] ./src/proteus/message/Message.js 2.17 kB {0} [built]
  [14] ./src/proteus/message/PreKeyMessage.js 3.17 kB {0} [built]
  [15] ./src/proteus/message/Envelope.js 3.76 kB {0} [built]
  [19] ./src/proteus/errors/InputError.js 1.75 kB {0} [built]
  [22] ./src/proteus/keys/PreKey.js 3.98 kB {0} [built]
  [23] ./src/proteus/keys/PreKeyBundle.js 5.14 kB {0} [built]
  [32] ./src/proteus.js 1.81 kB {0} [built]
    + 27 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (100 bytes).
This can impact web performance.
Assets: 
  proteus.js (187 kB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (300 bytes). This can impact web performance.
Entrypoints:
  filename (187 kB)
      proteus.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/


  CipherKey sanity checks (IETF ChaCha20 test vectors)
    ✓ encrypts plaintext to ciphertext
    ✓ decrypts ciphertext to plaintext

  Key Derivation Function (KDF)
    ✓ generates Cipher Key and Mac Key
    ✓ can encrypt and decrypt text

  Mac Key
    ✓ encodes a message

  DecryptError
    constructor
      ✓ constructs a default error code

  IdentityKeyPair
    ✓ serialises and deserialises

  KeyPair
    ✓ signs a message and verifies the signature
    ✓ computes a Diffie-Hellman shared secret

  PreKeyBundle
    ✓ should create a bundle
    ✓ should create a valid signed bundle
    ✓ should serialise and deserialise a unsigned bundle
    ✓ should serialise and deserialise a signed bundle
    ✓ should generate a serialised JSON format

  PreKey
    Generation
      ✓ should generate new PreKeys
      ✓ should reject invalid PreKey IDs
      ✓ throws errors with error codes
      ✓ generates ranges of PreKeys
      ✓ does not include the last resort pre key
    Serialisation
      ✓ should serialise and deserialise correctly

  Public Key
    ✓ should reject shared secrets at the point of infinity

  Envelope
    1) should encapsulate a CipherMessage
    2) should encapsulate a PreKeyMessage
    3) should encode to and decode from CBOR
    ✓ fails when passing invalid input

  Message
    4) should serialise and deserialise a CipherMessage correctly
    5) should serialise a PreKeyMessage correctly

  Session
    ✓ can be serialised and deserialised to/from CBOR
    6) encrypts and decrypts messages
    7) should limit the number of receive chains
    8) should handle a counter mismatch
    9) should handle multiple prekey messages
    10) should handle simultaneous prekey messages
    11) should handle simultaneous repeated messages
    12) should handle mass communication
    13) should fail retry init from message
    14) pathological case
    15) skipped message keys
    16) replaced prekeys
    17) max counter gap
    18) should limit the number of sessions

  HMAC-based Key Derivation Function
    ✓ concatenates buffers together

  HMAC RFC 5869 Test Vectors
    ✓ works with SHA-256 (Test Case 1 from RFC 5869)
    ✓ works with long key material
    ✓ works without salt

  HMAC Real World Scenarios
    ✓ works with a predefined data set

  MemoryUtil
    zeroize
      ✓ zeroizes an ArrayBuffer
      ✓ zeroizes an Uint8Array
      ✓ deeply zeroizes a KeyPair

  TypeUtil
    ✓ should check one type
    ✓ should check multiple types
    ✓ throws errors with error codes


  34 passing (4s)
  18 failing

  1) Envelope should encapsulate a CipherMessage:
     TypeError: Right-hand side of 'instanceof' is not callable
      at CipherMessage.serialise (src/proteus/message/Message.js:43:14)
      at Function.new (src/proteus/message/Envelope.js:51:55)
      at Context.it (test/message/EnvelopeSpec.js:34:45)

  2) Envelope should encapsulate a PreKeyMessage:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at Context.it (test/message/EnvelopeSpec.js:40:50)

  3) Envelope should encode to and decode from CBOR:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at Context.it (test/message/EnvelopeSpec.js:52:50)

  4) Message should serialise and deserialise a CipherMessage correctly:
     TypeError: Right-hand side of 'instanceof' is not callable
      at CipherMessage.serialise (src/proteus/message/Message.js:43:14)
      at Context.it (test/message/MessageSpec.js:44:38)

  5) Message should serialise a PreKeyMessage correctly:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at Context.it (test/message/MessageSpec.js:57:52)

  6) Session encrypts and decrypts messages:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Promise.all.map.text (test/session/SessionSpec.js:121:77)
      at Array.map (<anonymous>)
      at Proteus.session.Session.init_from_prekey.then.session (test/session/SessionSpec.js:121:59)
      at <anonymous>

  7) Session should limit the number of receive chains:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Proteus.session.Session.init_from_prekey.then.session (test/session/SessionSpec.js:207:22)
      at <anonymous>

  8) Session should handle a counter mismatch:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Proteus.session.Session.init_from_prekey.then.session (test/session/SessionSpec.js:263:22)
      at <anonymous>

  9) Session should handle multiple prekey messages:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Promise.all.map.text (test/session/SessionSpec.js:338:92)
      at Array.map (<anonymous>)
      at Proteus.session.Session.init_from_prekey.then.session (test/session/SessionSpec.js:338:74)
      at <anonymous>

  10) Session should handle simultaneous prekey messages:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Proteus.session.Session.init_from_prekey.then.session (test/session/SessionSpec.js:386:22)
      at <anonymous>

  11) Session should handle simultaneous repeated messages:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Proteus.session.Session.init_from_prekey.then.session (test/session/SessionSpec.js:455:22)
      at <anonymous>

  12) Session should handle mass communication:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Proteus.session.Session.init_from_prekey.then.session (test/session/SessionSpec.js:541:22)
      at <anonymous>

  13) Session should fail retry init from message:
     AssertionError: expected [TypeError: Right-hand side of 'instanceof' is not callable] to be an instance of func
      at Proteus.session.Session.init_from_prekey.then.then.then.then.catch.err (test/session/SessionSpec.js:601:16)
      at <anonymous>

  14) Session pathological case:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Promise.all.then.session (test/session/SessionSpec.js:631:26)
      at <anonymous>

  15) Session skipped message keys:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Proteus.session.Session.init_from_prekey.then.session (test/session/SessionSpec.js:686:22)
      at <anonymous>

  16) Session replaced prekeys:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Proteus.session.Session.init_from_prekey.then.session (test/session/SessionSpec.js:819:22)
      at <anonymous>

  17) Session max counter gap:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Proteus.session.Session.init_from_prekey.then.session (test/session/SessionSpec.js:868:22)
      at <anonymous>

  18) Session should limit the number of sessions:
     TypeError: Right-hand side of 'instanceof' is not callable
      at classes.some.k (src/proteus/util/TypeUtil.js:37:32)
      at Array.some (<anonymous>)
      at Object.assert_is_instance (src/proteus/util/TypeUtil.js:37:17)
      at Function.new (src/proteus/message/PreKeyMessage.js:57:14)
      at SessionState.encrypt (src/proteus/session/SessionState.js:190:34)
      at Promise (src/proteus/session/Session.js:264:21)
      at new Promise (<anonymous>)
      at Session.encrypt (src/proteus/session/Session.js:251:12)
      at Proteus.session.Session.init_from_prekey.then.session_alice (test/session/SessionSpec.js:912:22)
      at <anonymous>



error Command failed with exit code 18.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

**Comment by bennyn** [comment]
Thanks Lipis but the project will be moved to https://github.com/wireapp/wire-web-packages and then it will have Prettier by default.

**Pull request closed without merging**
